input.onButtonPressed(Button.A, function () {
    strip.setPixelColor(0, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(1, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(2, neopixel.colors(NeoPixelColors.Yellow))
    strip.setPixelColor(3, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(4, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(5, neopixel.colors(NeoPixelColors.Indigo))
    strip.setPixelColor(6, neopixel.colors(NeoPixelColors.Violet))
    strip.setPixelColor(7, neopixel.colors(NeoPixelColors.Purple))
    strip.setPixelColor(8, neopixel.colors(NeoPixelColors.Violet))
    strip.setPixelColor(9, neopixel.colors(NeoPixelColors.Indigo))
    strip.setPixelColor(10, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(11, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(12, neopixel.colors(NeoPixelColors.Yellow))
    strip.setPixelColor(13, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(14, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(15, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(16, neopixel.colors(NeoPixelColors.Yellow))
    strip.setPixelColor(17, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(18, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(19, neopixel.colors(NeoPixelColors.Indigo))
    strip.setPixelColor(20, neopixel.colors(NeoPixelColors.Violet))
    strip.setPixelColor(21, neopixel.colors(NeoPixelColors.Purple))
    strip.setPixelColor(22, neopixel.colors(NeoPixelColors.Violet))
    strip.setPixelColor(23, neopixel.colors(NeoPixelColors.Indigo))
    strip.setPixelColor(24, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(25, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(26, neopixel.colors(NeoPixelColors.Yellow))
    strip.setPixelColor(27, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(28, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(29, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(30, neopixel.colors(NeoPixelColors.Yellow))
    strip.setPixelColor(31, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(32, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(33, neopixel.colors(NeoPixelColors.Indigo))
    strip.setPixelColor(34, neopixel.colors(NeoPixelColors.Violet))
    strip.setPixelColor(35, neopixel.colors(NeoPixelColors.Purple))
    strip.setPixelColor(36, neopixel.colors(NeoPixelColors.Violet))
    strip.setPixelColor(37, neopixel.colors(NeoPixelColors.Indigo))
    strip.setPixelColor(38, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(39, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(40, neopixel.colors(NeoPixelColors.Yellow))
    strip.setPixelColor(41, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(42, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(43, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(44, neopixel.colors(NeoPixelColors.Yellow))
    strip.setPixelColor(45, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(46, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(47, neopixel.colors(NeoPixelColors.Indigo))
    strip.setPixelColor(48, neopixel.colors(NeoPixelColors.Violet))
    strip.setPixelColor(49, neopixel.colors(NeoPixelColors.Purple))
    strip.setPixelColor(50, neopixel.colors(NeoPixelColors.Violet))
    strip.setPixelColor(51, neopixel.colors(NeoPixelColors.Indigo))
    strip.setPixelColor(52, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(53, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(54, neopixel.colors(NeoPixelColors.Yellow))
    strip.setPixelColor(55, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(56, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(57, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(58, neopixel.colors(NeoPixelColors.Yellow))
    strip.setPixelColor(59, neopixel.colors(NeoPixelColors.Orange))
    strip.show()
})
input.onButtonPressed(Button.AB, function () {
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
})
input.onButtonPressed(Button.B, function () {
    strip.showRainbow(1, 360)
})
let strip: neopixel.Strip = null
strip = neopixel.create(DigitalPin.P1, 60, NeoPixelMode.RGB)
strip.showColor(neopixel.colors(NeoPixelColors.Black))
